--EXCEPTIONS 40 - 50 USE COMMENT DOESNT EXISTS

---40 create comment error check the entered data
---41 delete comment error check the entered data
---42 comment with that id does not exist
-- 43 error when reading comments
-- 44 comment with that photo id does not exist
--------------------------------------------------------------------------------
CREATE PUBLIC SYNONYM ADD_COMMENT FOR FISHY_ADMIN.ADD_COMMENT;
--DROP PUBLIC SYNONYM ADD_COMMENT;

--DROP PROCEDURE ADD_COMMENT;
CREATE OR REPLACE PROCEDURE ADD_COMMENT(
  COMMENT_INFO IN COMMENTS.INFO%TYPE,
  COMMENT_PHOTO_ID IN COMMENTS.PHOTO_ID%TYPE,
  OWNER_ID IN COMMENTS.USER_ID%TYPE)
IS
BEGIN
  INSERT INTO COMMENTS(INFO,PHOTO_ID,USER_ID,CREATED) 
    VALUES(COMMENT_INFO,COMMENT_PHOTO_ID,OWNER_ID,CURRENT_TIMESTAMP);
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20040, 'create comment error check the entered data');
END ADD_COMMENT;
--------------------------------------------------------------------------------
CREATE PUBLIC SYNONYM DELETE_COMMENT_BY_ID FOR FISHY_ADMIN.DELETE_COMMENT_BY_ID;
--DROP PUBLIC SYNONYM DELETE_COMMENT_BY_ID;

--DROP PROCEDURE DELETE_COMMENT_BY_ID;
CREATE OR REPLACE PROCEDURE DELETE_COMMENT_BY_ID(
COMMENT_ID IN COMMENTS.ID%TYPE)
IS
  COMMENT_COUNTER NUMBER;
BEGIN
  SELECT COUNT(*) INTO COMMENT_COUNTER 
    FROM COMMENTS 
      WHERE ID = COMMENT_ID;
  IF COMMENT_COUNTER = 0 THEN
    RAISE EXCEPTION_PACKAGE.COMMENT_DOESNT_EXISTS;
  ELSE
    DELETE COMMENTS WHERE ID = COMMENT_ID;
  END IF;
  COMMIT;
EXCEPTION
    WHEN EXCEPTION_PACKAGE.COMMENT_DOESNT_EXISTS THEN
      RAISE_APPLICATION_ERROR(-20042, 'comment with that id does not exist');
    
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20041, 'delete comment error check the entered data');
END DELETE_COMMENT_BY_ID;
--------------------------------------------------------------------------------
CREATE PUBLIC SYNONYM DELETE_COMMENT_BY_PHOTO_ID FOR FISHY_ADMIN.DELETE_COMMENT_BY_PHOTO_ID;
--DROP PUBLIC SYNONYM DELETE_COMMENT_BY_PHOTO_ID;

--DROP PROCEDURE DELETE_COMMENT_BY_PHOTO_ID;
CREATE OR REPLACE PROCEDURE DELETE_COMMENT_BY_PHOTO_ID(
COMMENT_PHOTO_ID IN COMMENTS.PHOTO_ID%TYPE)
IS
  COMMENT_COUNTER NUMBER;
BEGIN
  SELECT COUNT(*) INTO COMMENT_COUNTER 
    FROM COMMENTS 
      WHERE PHOTO_ID = COMMENT_PHOTO_ID;
  IF COMMENT_COUNTER = 0 THEN
    RAISE EXCEPTION_PACKAGE.COMMENT_DOESNT_EXISTS;
  ELSE
    DELETE COMMENTS
      WHERE PHOTO_ID = COMMENT_PHOTO_ID;
  END IF;
  COMMIT;
EXCEPTION
    WHEN EXCEPTION_PACKAGE.COMMENT_DOESNT_EXISTS THEN
      RAISE_APPLICATION_ERROR(-20044, 'comment with that photo id does not exist');
    
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20041, 'delete comment error check the entered data');
END DELETE_COMMENT_BY_PHOTO_ID;
--------------------------------------------------------------------------------
CREATE PUBLIC SYNONYM GET_COMMENTS_BY_PHOTO_ID FOR FISHY_ADMIN.GET_COMMENTS_BY_PHOTO_ID;
--DROP PUBLIC SYNONYM GET_COMMENTS_BY_PHOTO_ID;

--DROP PROCEDURE GET_COMMENTS_BY_PHOTO_ID;
CREATE OR REPLACE PROCEDURE GET_COMMENTS_BY_PHOTO_ID(
RESULT_CURSOR OUT SYS_REFCURSOR,
P_ID IN COMMENTS_VIEW.PHOTO_ID%TYPE)
IS
BEGIN
  OPEN RESULT_CURSOR FOR 
  SELECT COMMENT_ID,COMMENT_INFO,COMMENT_CREATED,OWNER_ID,OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_AVATAR 
    FROM COMMENTS_VIEW 
      WHERE PHOTO_ID = P_ID 
        ORDER BY COMMENT_CREATED DESC;
EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20043, 'error when reading comments');
END GET_COMMENTS_BY_PHOTO_ID;
--------------------------------------------------------------------------------
CREATE PUBLIC SYNONYM GET_COMMENT_BY_ID FOR FISHY_ADMIN.GET_COMMENT_BY_ID;
--DROP PUBLIC SYNONYM GET_COMMENT_BY_ID;

--DROP PROCEDURE GET_COMMENT_BY_ID;
CREATE OR REPLACE PROCEDURE GET_COMMENT_BY_ID(
RESULT_CURSOR OUT SYS_REFCURSOR,
C_ID IN COMMENTS_VIEW.COMMENT_ID%TYPE)
IS
BEGIN
  OPEN RESULT_CURSOR FOR 
    SELECT COMMENT_ID,COMMENT_INFO,COMMENT_CREATED,OWNER_ID,OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_AVATAR 
      FROM COMMENTS_VIEW 
        WHERE COMMENT_ID = C_ID;
EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20043, 'error when reading comments');
END GET_COMMENT_BY_ID;
--------------------------------------------------------------------------------

