------------------------------EXCEPTION_PACKAGE---------------------------------
--DROP PACKAGE EXCEPTION_PACKAGE;
CREATE OR REPLACE PACKAGE EXCEPTION_PACKAGE IS
  EMAIL_ALREADY_EXISTS EXCEPTION;
  INCORRECTLY_EMAIL EXCEPTION;
  INCORRECTLY_PHONE EXCEPTION;
  
  FRIEND_ALREADY_EXISTS EXCEPTION;
  FRIEND_DOESNT_EXISTS EXCEPTION;
  
  ALBUM_ALREADY_EXISTS EXCEPTION;
  ALBUM_DOESNT_EXISTS EXCEPTION;
  
  PHOTO_DOESNT_EXISTS EXCEPTION;
  COMMENT_DOESNT_EXISTS EXCEPTION;
  
  DIALOG_DOESNT_EXISTS EXCEPTION;
  NO_PRIVILEGES EXCEPTION;
  USER_ALREADY_IN_DIALOG EXCEPTION;
  USER_DOESNT_IN_DIALOG EXCEPTION;
  
  NOT_FOUND_USER_IN_DIALOG EXCEPTION;
  
  NEWS_ALREADY_EXISTS EXCEPTION;
  NEWS_DOESNT_EXISTS EXCEPTION;

  FISH_ALREADY_EXISTS EXCEPTION;
  FISH_DOESNT_EXISTS EXCEPTION;
  
  INSPECTION_ALREADY_EXISTS EXCEPTION;
  INSPECTION_DOESNT_EXISTS EXCEPTION;
END;