SET serveroutput ON;
------------------------------------USERS---------------------------------------
DECLARE
C NUMBER := 100000;
U USERS%ROWTYPE;
BEGIN
  DBMS_RANDOM.SEED(6);
  LOOP
  EXIT WHEN C = 0;
    U.FIRST_NAME := DBMS_RANDOM.STRING('A',7);
    U.LAST_NAME := DBMS_RANDOM.STRING('A',8);
    U.EMAIL := DBMS_RANDOM.STRING('L',9)||'@gmail.com';
    U.PASS := DBMS_RANDOM.STRING('P',7);
    IF MOD(C,2) = 0 THEN
      SELECT MAX(ID) INTO U.ID FROM USERS;
      U.AGE := DBMS_RANDOM.VALUE(12,100);
      U.INFO := DBMS_RANDOM.STRING('A',150);
      U.AVATAR := 'https://loclalhost:3000/photos/'||CEIL(DBMS_RANDOM.VALUE(1,1000));
      
      CHANGE_AGE(U.ID,U.AGE);
      CHANGE_INFO(U.ID,U.INFO);
      CHANGE_AVATAR(U.ID,U.AVATAR);
    END IF;
    BEGIN
    REGISTRATION(U.FIRST_NAME,U.LAST_NAME,U.EMAIL,U.PASS);
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(SQLERRM);
    END;
    C := C-1;
  END LOOP;
  COMMIT;
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;

SELECT * FROM USERS;
DELETE USERS;
----------------------------------FRIENDS---------------------------------------
DECLARE
CURSOR CS IS SELECT ID FROM USERS;
CF NUMBER := 3;
M_X NUMBER;
M_N NUMBER;
U_ID NUMBER;
BEGIN
  DBMS_RANDOM.SEED(8);
  SELECT MAX(ID) INTO M_X FROM USERS;
  SELECT MIN(ID) INTO M_N FROM USERS;

  OPEN CS;
  LOOP
  FETCH CS INTO U_ID;
  EXIT WHEN CS%NOTFOUND;
    BEGIN
    LOOP
    EXIT WHEN CF = 0;
      BEGIN
        ADD_FRIEND(U_ID,DBMS_RANDOM.VALUE(M_N,M_X));
      EXCEPTION WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
      END;
      CF := CF-1;
    END LOOP;
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(SQLERRM);
    END;
    CF := 10;
  END LOOP;
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;

SELECT * FROM FRIENDS;
DELETE FRIENDS;
----------------------------------ALBUMS----------------------------------------
DECLARE
CURSOR CS IS SELECT ID FROM USERS;
CA NUMBER := 5;
U_ID NUMBER;
BEGIN
  DBMS_RANDOM.SEED(4);
  
  OPEN CS;
  LOOP
  FETCH CS INTO U_ID;
  EXIT WHEN CS%NOTFOUND;
    LOOP
    EXIT WHEN CA = 0;
      BEGIN
        ADD_ALBUM(U_ID||'ALBUM '||CA,U_ID);
      EXCEPTION WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
      END;
      CA := CA - 1;
    END LOOP;
  CA := 5;
  END LOOP;
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;

SELECT * FROM ALBUMS;
SELECT COUNT(*) FROM ALBUMS;
DELETE ALBUMS;
----------------------------------PHOTOS----------------------------------------
DECLARE
CURSOR CS IS SELECT ID FROM ALBUMS;
CA NUMBER := 3;
A_ID NUMBER;
LNG NUMBER;
LAT NUMBER;
BEGIN
  DBMS_RANDOM.SEED(5);
  OPEN CS;
  LOOP
  FETCH CS INTO A_ID;
  EXIT WHEN CS%NOTFOUND;
    LOOP
    EXIT WHEN CA = 0;
      LNG := ROUND(DBMS_RANDOM.VALUE(0,90),4);
      LAT := ROUND(DBMS_RANDOM.VALUE(0,90),4);
      BEGIN
      ADD_PHOTO('https://albums/'||A_ID||'/photo/'||CA,A_ID,LNG,LAT);
      EXCEPTION WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
      END;
      CA := CA - 1;
    END LOOP;
  CA := 3;
  END LOOP;
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;

SELECT * FROM PHOTOS;
DELETE PHOTOS;
----------------------------------COMMENTS--------------------------------------
DECLARE
CURSOR CS IS SELECT ID FROM PHOTOS;
CA NUMBER := 3;
P_ID NUMBER;
U_ID NUMBER;
BEGIN
  DBMS_RANDOM.SEED(5);
  SELECT CEIL(AVG(ID)) INTO U_ID FROM USERS;
  OPEN CS;
  LOOP
  FETCH CS INTO P_ID;
  EXIT WHEN CS%NOTFOUND;
    LOOP
    EXIT WHEN CA = 0;
      BEGIN
        ADD_COMMENT(P_ID + U_ID||'COMMENT'||CA,P_ID,U_ID + CA);
      EXCEPTION WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
      END;
      CA := CA - 1;
    END LOOP;
  CA := 3;
  END LOOP;
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;

SELECT * FROM COMMENTS;
DELETE COMMENTS;
----------------------------------DIALOGS---------------------------------------
DECLARE
CURSOR CS IS SELECT ID FROM USERS WHERE ID < (SELECT CEIL(AVG(ID)/2) FROM USERS);
CA NUMBER := 2;
U_ID NUMBER;
D_ID NUMBER;
TFP NUMBER ;
BEGIN
  DBMS_RANDOM.SEED(5);
  SELECT CEIL(MAX(ID)/2) INTO TFP FROM USERS;
  OPEN CS;
  LOOP
  FETCH CS INTO U_ID;
  EXIT WHEN CS%NOTFOUND;
    LOOP
    EXIT WHEN CA = 0;
      BEGIN
        ADD_DIALOG(U_ID,'DIALOG'||U_ID);
        SELECT MAX(ID) INTO D_ID FROM DIALOGS ;
        INVITE_USER_TO_DIALOG(U_ID + TFP - 2*CA,D_ID);
      EXCEPTION WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
      END;
      CA := CA - 1;
    END LOOP;
  CA := 2;
  END LOOP;
  COMMIT;
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;

SELECT * FROM USERS;
SELECT * FROM DIALOGS;
SELECT * FROM DIALOGS_VIEW;
DELETE DIALOGS;
----------------------------------MESSAGES--------------------------------------
DECLARE
TYPE REFCURSOR IS REF CURSOR;
CURSOR CS IS
  SELECT DIALOG_ID,CURSOR(SELECT USER_ID FROM DIALOGS_VIEW MWW WHERE MWW.DIALOG_ID = MW.DIALOG_ID) 
    FROM DIALOGS_VIEW MW
      GROUP BY DIALOG_ID;
D_ID MESSAGES_VIEW.DIALOG_ID%TYPE;
U_ID MESSAGES_VIEW.USER_ID%TYPE;
CR REFCURSOR;
BEGIN
  OPEN CS;
  LOOP
  FETCH CS INTO D_ID,CR;
  EXIT WHEN CS%NOTFOUND;
    LOOP
    FETCH CR INTO U_ID;
    EXIT WHEN CR%NOTFOUND;
      BEGIN
        ADD_MESSAGE(U_ID||D_ID||'MESS1',U_ID,D_ID);
        ADD_MESSAGE(D_ID||U_ID||'MESS2',U_ID,D_ID);
      EXCEPTION WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
      END;
    END LOOP;
  END LOOP;
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;

SELECT * FROM MESSAGES;
SELECT * FROM MESSAGES_VIEW;
DELETE MESSAGES;
-------------------------------------NEWS---------------------------------------
DECLARE
C NUMBER := 10;
N NEWS%ROWTYPE;
BEGIN
  DBMS_RANDOM.SEED(2);
  LOOP
  EXIT WHEN C = 0;
    N.TITLE := DBMS_RANDOM.STRING('A',4)||'news title';
    N.INFO := DBMS_RANDOM.STRING('A',2)||'INFO'||DBMS_RANDOM.STRING('A',200);
    N.PHOTO := 'https://loclalhost:3000/news/photos/'||CEIL(DBMS_RANDOM.VALUE(1,1000));
    
    BEGIN
      ADD_NEWS(N.TITLE,N.INFO,N.PHOTO,5);
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(SQLERRM);
    END;
    C := C-1;
  END LOOP;
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;

SELECT * FROM NEWS;
DELETE NEWS;
----------------------------------FISHES----------------------------------------
DECLARE
C NUMBER := 10;
F FISHES%ROWTYPE;
BEGIN
  DBMS_RANDOM.SEED(2);
  LOOP
  EXIT WHEN C = 0;
    F.NAME := DBMS_RANDOM.STRING('A',4)||'FISH';
    F.INFO := 'INFO'||DBMS_RANDOM.STRING('A',200);
    F.PHOTO := 'https://loclalhost:3000/fishes/photos/'||CEIL(DBMS_RANDOM.VALUE(1,1000));
    
    BEGIN
        ADD_FISH(F.NAME,F.INFO,F.PHOTO,5);
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(SQLERRM);
    END;
    C := C-1;
  END LOOP;
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;

SELECT * FROM FISHES;
DELETE FISHES;
----------------------------------INSPECTIONS-----------------------------------
DECLARE
C NUMBER := 10;
I STATE_INSPECTIONS%ROWTYPE;
BEGIN
  DBMS_RANDOM.SEED(2);
  LOOP
  EXIT WHEN C = 0;
    I.REGION := 'REGION'||DBMS_RANDOM.STRING('A',4);
    I.ADDRESS := 'ADRESS'||DBMS_RANDOM.STRING('A',20);
    I.PHONE := '+37529'||CEIL(DBMS_RANDOM.VALUE(10000,100000))||CEIL(DBMS_RANDOM.VALUE(10,100));
    
    BEGIN
      ADD_INSPECTION(I.REGION,I.ADDRESS,I.PHONE,5);
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(SQLERRM);
    END;
    C := C-1;
  END LOOP;
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;

SELECT * FROM STATE_INSPECTIONS;
DELETE STATE_INSPECTIONS;
--------------------------------------------------------------------------------